/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static ui.UI.cnt;

/**
 *
 * @author Aditya Mhatre
 */
public class AddQuestion extends javax.swing.JFrame {

    public static int x;
    public static String level;
    /**
     * Creates new form AddQuestion
     */
    public AddQuestion() {
        initComponents();
        Countrow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGQue = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JButton();
        Menu1 = new javax.swing.JButton();
        AnsAQ = new javax.swing.JLabel();
        QueAQ = new javax.swing.JLabel();
        OP1AQ = new javax.swing.JLabel();
        OP2AQ = new javax.swing.JLabel();
        OP3AQ = new javax.swing.JLabel();
        OP4AQ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        QueF = new javax.swing.JTextArea();
        AnsF = new javax.swing.JTextField();
        OP1F = new javax.swing.JTextField();
        OP2F = new javax.swing.JTextField();
        OP3F = new javax.swing.JTextField();
        OP4F = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        opt8 = new javax.swing.JRadioButton();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        opt5 = new javax.swing.JRadioButton();
        opt6 = new javax.swing.JRadioButton();
        opt7 = new javax.swing.JRadioButton();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(750, 496));
        setMinimumSize(new java.awt.Dimension(750, 496));
        setPreferredSize(new java.awt.Dimension(750, 496));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 496));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(79, 0, 188));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(76, 76, 76));
        Menu.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Log Out");
        Menu.setBorder(null);
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setFocusPainted(false);
        Menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        Menu1.setBackground(new java.awt.Color(76, 76, 76));
        Menu1.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        Menu1.setForeground(new java.awt.Color(255, 255, 255));
        Menu1.setText("Menu");
        Menu1.setBorder(null);
        Menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu1.setFocusPainted(false);
        Menu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu1MouseClicked(evt);
            }
        });
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });
        jPanel2.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 90));

        AnsAQ.setBackground(new java.awt.Color(255, 255, 255));
        AnsAQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AnsAQ.setForeground(new java.awt.Color(255, 255, 255));
        AnsAQ.setText("Answer :");
        jPanel1.add(AnsAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 70, -1));

        QueAQ.setBackground(new java.awt.Color(255, 255, 255));
        QueAQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        QueAQ.setForeground(new java.awt.Color(255, 255, 255));
        QueAQ.setText("Question :");
        jPanel1.add(QueAQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        OP1AQ.setBackground(new java.awt.Color(255, 255, 255));
        OP1AQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OP1AQ.setForeground(new java.awt.Color(255, 255, 255));
        OP1AQ.setText("Option 1 :");
        jPanel1.add(OP1AQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, -1));

        OP2AQ.setBackground(new java.awt.Color(255, 255, 255));
        OP2AQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OP2AQ.setForeground(new java.awt.Color(255, 255, 255));
        OP2AQ.setText("Option 2 :");
        jPanel1.add(OP2AQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, -1));

        OP3AQ.setBackground(new java.awt.Color(255, 255, 255));
        OP3AQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OP3AQ.setForeground(new java.awt.Color(255, 255, 255));
        OP3AQ.setText("Option 3 :");
        jPanel1.add(OP3AQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 70, -1));

        OP4AQ.setBackground(new java.awt.Color(255, 255, 255));
        OP4AQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OP4AQ.setForeground(new java.awt.Color(255, 255, 255));
        OP4AQ.setText("Option 4 :");
        jPanel1.add(OP4AQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, -1));

        QueF.setBackground(new java.awt.Color(79, 0, 188));
        QueF.setColumns(20);
        QueF.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        QueF.setForeground(new java.awt.Color(255, 255, 255));
        QueF.setLineWrap(true);
        QueF.setRows(4);
        QueF.setWrapStyleWord(true);
        QueF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        QueF.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(QueF);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 470, 80));

        AnsF.setBackground(new java.awt.Color(79, 0, 188));
        AnsF.setForeground(new java.awt.Color(255, 255, 255));
        AnsF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        AnsF.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(AnsF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 470, 30));

        OP1F.setBackground(new java.awt.Color(79, 0, 188));
        OP1F.setForeground(new java.awt.Color(255, 255, 255));
        OP1F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        OP1F.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(OP1F, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 470, 30));

        OP2F.setBackground(new java.awt.Color(79, 0, 188));
        OP2F.setForeground(new java.awt.Color(255, 255, 255));
        OP2F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        OP2F.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(OP2F, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 470, 30));

        OP3F.setBackground(new java.awt.Color(79, 0, 188));
        OP3F.setForeground(new java.awt.Color(255, 255, 255));
        OP3F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        OP3F.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(OP3F, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 470, 30));

        OP4F.setBackground(new java.awt.Color(79, 0, 188));
        OP4F.setForeground(new java.awt.Color(255, 255, 255));
        OP4F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        OP4F.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(OP4F, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 470, 30));

        Update.setBackground(new java.awt.Color(99, 0, 237));
        Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update");
        Update.setBorder(null);
        Update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Update.setFocusPainted(false);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 150, 30));

        opt8.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt8);
        opt8.setForeground(new java.awt.Color(255, 255, 255));
        opt8.setText("Question 8");
        opt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt8ActionPerformed(evt);
            }
        });
        jPanel1.add(opt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        opt1.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt1);
        opt1.setForeground(new java.awt.Color(255, 255, 255));
        opt1.setSelected(true);
        opt1.setText("Question 1");
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });
        jPanel1.add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        opt2.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt2);
        opt2.setForeground(new java.awt.Color(255, 255, 255));
        opt2.setText("Question 2");
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });
        jPanel1.add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        opt3.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt3);
        opt3.setForeground(new java.awt.Color(255, 255, 255));
        opt3.setText("Question 3");
        opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3ActionPerformed(evt);
            }
        });
        jPanel1.add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        opt4.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt4);
        opt4.setForeground(new java.awt.Color(255, 255, 255));
        opt4.setText("Question 4");
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });
        jPanel1.add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        opt5.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt5);
        opt5.setForeground(new java.awt.Color(255, 255, 255));
        opt5.setText("Question 5");
        opt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt5ActionPerformed(evt);
            }
        });
        jPanel1.add(opt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        opt6.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt6);
        opt6.setForeground(new java.awt.Color(255, 255, 255));
        opt6.setText("Question 6");
        opt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt6ActionPerformed(evt);
            }
        });
        jPanel1.add(opt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        opt7.setBackground(new java.awt.Color(79, 0, 188));
        BGQue.add(opt7);
        opt7.setForeground(new java.awt.Color(255, 255, 255));
        opt7.setText("Question 7");
        opt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt7ActionPerformed(evt);
            }
        });
        jPanel1.add(opt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        Add.setBackground(new java.awt.Color(99, 0, 237));
        Add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setBorder(null);
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.setFocusPainted(false);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 150, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        String s1 = "delete from "+AddQuestion.level+" where qnum = "+x+"";
        String s2 = "insert into "+level+" values("+x+",'"+QueF.getText()+"','"+OP1F.getText()+"','"+OP2F.getText()+"','"+OP3F.getText()+"','"+OP4F.getText()+"','"+AnsF.getText()+"')";
        DBCon.connect();
        DBCon.executeUpdate(s1);
        DBCon.executeUpdate(s2);
        DBCon.disconnect();
        SignUp_Page.statement.setText("Updating Question Completed");
        SignUp_Page.Correct.setVisible(true);
    }//GEN-LAST:event_UpdateActionPerformed

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        SignUp_Page hp;
        try {
            hp = new SignUp_Page();
            Questions.score=0;
            Questions.i=1;
            hp.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MenuStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MenuMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
            String add = "insert into "+level+" values("+x+",'"+QueF.getText()+"','"+OP1F.getText()+"','"+OP2F.getText()+"','"+OP3F.getText()+"','"+OP4F.getText()+"','"+AnsF.getText()+"')";   
                DBCon.connect();
                int x = DBCon.executeUpdate(add);
                DBCon.disconnect();
                Countrow();
                SignUp_Page.statement.setText("Adding Question Completed");
                SignUp_Page.Correct.setVisible(true);
            
    }//GEN-LAST:event_AddActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        try {
            // TODO add your handling code here:
            updateBoxes(1);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt1ActionPerformed

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(2);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(3);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt3ActionPerformed

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(4);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt4ActionPerformed

    private void opt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(5);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt5ActionPerformed

    private void opt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt6ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(6);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt6ActionPerformed

    private void opt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(7);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt7ActionPerformed

    private void opt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt8ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            updateBoxes(8);
        } catch (SQLException ex) {
            Logger.getLogger(AddQuestion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_opt8ActionPerformed

    private void Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseClicked
        // TODO add your handling code here:
        MenuFaculty hp;
        try {
            hp = new MenuFaculty();
            hp.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(MenuStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Menu1MouseClicked

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu1ActionPerformed

    public void Countrow()  {
        try (
            ResultSet rs = DBCon.executeQuery("select count(qnum) as count from "+AddQuestion.level+"")) {
            System.out.println("Count");
            while(rs.next())
            {
                UI.cnt = rs.getInt("Count");
                System.out.println(cnt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void updateBoxes(int i) throws SQLException    {
        if(i<=UI.cnt)    {
            DBCon.connect();
            ResultSet rs = DBCon.executeQuery("select * from "+AddQuestion.level+" where qnum = "+i);
            while(rs.next())  {
                QueF.setText(rs.getString("ques"));
                OP1F.setText(rs.getString("opt1"));
                OP2F.setText(rs.getString("opt2"));
                OP3F.setText(rs.getString("opt3"));
                OP4F.setText(rs.getString("opt4"));
                AnsF.setText(rs.getString("answer"));
                Countrow();
            }
        }
        else
        {
            QueF.setText("");
                OP1F.setText("");
                OP2F.setText("");
                OP3F.setText("");
                OP4F.setText("");
                AnsF.setText("");
        }
        AddQuestion.x = i;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel AnsAQ;
    private javax.swing.JTextField AnsF;
    private javax.swing.ButtonGroup BGQue;
    private javax.swing.JButton Menu;
    private javax.swing.JButton Menu1;
    private javax.swing.JLabel OP1AQ;
    private javax.swing.JTextField OP1F;
    private javax.swing.JLabel OP2AQ;
    private javax.swing.JTextField OP2F;
    private javax.swing.JLabel OP3AQ;
    private javax.swing.JTextField OP3F;
    private javax.swing.JLabel OP4AQ;
    private javax.swing.JTextField OP4F;
    private javax.swing.JLabel QueAQ;
    private javax.swing.JTextArea QueF;
    private javax.swing.JButton Update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JRadioButton opt5;
    private javax.swing.JRadioButton opt6;
    private javax.swing.JRadioButton opt7;
    private javax.swing.JRadioButton opt8;
    // End of variables declaration//GEN-END:variables
}
