/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Aditya Mhatre
 */
public class TableView extends javax.swing.JFrame {
public static String username;
    /**
     * Creates new form TableView
     */
    public TableView() {
        initComponents();
        String sql="select * from scorecard";
        ResultSet rs = DBCon.executeQuery(sql);
        ScoreTable.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    void LoadSampleData()   {
        try
        {
            DBCon.connect();
            ResultSet rs=DBCon.executeQuery("select * from scorecard");
                    while(ScoreTable.getRowCount()>0)
                    {  
                        ((DefaultTableModel)ScoreTable.getModel()).removeRow(0);
                    }
                    int col = rs.getMetaData().getColumnCount();
                    while(rs.next())
                    {
                        Object rows[] = new Object[col];
                        for(int i=1; i<=col; i++)
                            rows[i-1] = rs.getObject(i);
                        
                        ((DefaultTableModel)ScoreTable.getModel()).insertRow(rs.getRow()-1, rows);
                    }
            rs.close();
            DBCon.disconnect();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScoreTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JButton();
        SBName = new javax.swing.JButton();
        GBLevel3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SBScore = new javax.swing.JButton();
        GBLevel1 = new javax.swing.JButton();
        GBLevel2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jButton5.setBackground(new java.awt.Color(84, 84, 84));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Score");
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(307, 130));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(752, 508));
        setMinimumSize(new java.awt.Dimension(752, 508));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScoreTable.setAutoCreateRowSorter(true);
        ScoreTable.setForeground(new java.awt.Color(51, 51, 51));
        ScoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Level", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ScoreTable.setAutoscrolls(false);
        ScoreTable.setGridColor(new java.awt.Color(204, 204, 204));
        ScoreTable.setRowSelectionAllowed(false);
        ScoreTable.setSelectionBackground(new java.awt.Color(51, 51, 51));
        ScoreTable.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(ScoreTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 590, 430));

        jPanel2.setBackground(new java.awt.Color(79, 0, 188));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(99, 0, 237));
        Menu.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setText("Menu");
        Menu.setBorder(null);
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setFocusPainted(false);
        Menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 80));

        SBName.setBackground(new java.awt.Color(84, 84, 84));
        SBName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SBName.setForeground(new java.awt.Color(255, 255, 255));
        SBName.setText("Name");
        SBName.setBorder(null);
        SBName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SBName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBNameActionPerformed(evt);
            }
        });
        jPanel1.add(SBName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 60));

        GBLevel3.setBackground(new java.awt.Color(84, 84, 84));
        GBLevel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GBLevel3.setForeground(new java.awt.Color(255, 255, 255));
        GBLevel3.setText("Level 3");
        GBLevel3.setBorder(null);
        GBLevel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GBLevel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBLevel3ActionPerformed(evt);
            }
        });
        jPanel1.add(GBLevel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 160, 60));

        jLabel1.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SHOW BY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 160, 60));

        jLabel3.setFont(new java.awt.Font("Gotham Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SORT BY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 60));

        SBScore.setBackground(new java.awt.Color(84, 84, 84));
        SBScore.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SBScore.setForeground(new java.awt.Color(255, 255, 255));
        SBScore.setText("Score");
        SBScore.setBorder(null);
        SBScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SBScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBScoreActionPerformed(evt);
            }
        });
        jPanel1.add(SBScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 160, 60));

        GBLevel1.setBackground(new java.awt.Color(84, 84, 84));
        GBLevel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GBLevel1.setForeground(new java.awt.Color(255, 255, 255));
        GBLevel1.setText("Level 1");
        GBLevel1.setBorder(null);
        GBLevel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GBLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBLevel1ActionPerformed(evt);
            }
        });
        jPanel1.add(GBLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 160, 60));

        GBLevel2.setBackground(new java.awt.Color(84, 84, 84));
        GBLevel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GBLevel2.setForeground(new java.awt.Color(255, 255, 255));
        GBLevel2.setText("Level 2");
        GBLevel2.setBorder(null);
        GBLevel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GBLevel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBLevel2ActionPerformed(evt);
            }
        });
        jPanel1.add(GBLevel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        MenuStudent ms = new MenuStudent();
        ms.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuMouseClicked

    private void GBLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBLevel1ActionPerformed
        // TODO add your handling code here:
        String sql="select * from scorecard where subject = 'level_1'";
        ResultSet rs = DBCon.executeQuery(sql);
        ScoreTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_GBLevel1ActionPerformed

    private void SBScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBScoreActionPerformed
        // TODO add your handling code here:
        String sql="select * from scorecard order by score DESC";
        ResultSet rs = DBCon.executeQuery(sql);
        ScoreTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_SBScoreActionPerformed

    private void GBLevel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBLevel2ActionPerformed
        // TODO add your handling code here:
        String sql="select * from scorecard where subject = 'level_2'";
        ResultSet rs = DBCon.executeQuery(sql);
        ScoreTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_GBLevel2ActionPerformed

    private void GBLevel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBLevel3ActionPerformed
        // TODO add your handling code here:
        String sql="select * from scorecard where subject = 'level_3'";
        ResultSet rs = DBCon.executeQuery(sql);
        ScoreTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_GBLevel3ActionPerformed

    private void SBNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBNameActionPerformed
        // TODO add your handling code here:
        String sql="select * from scorecard order by username ASC";
        ResultSet rs = DBCon.executeQuery(sql);
        ScoreTable.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_SBNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GBLevel1;
    private javax.swing.JButton GBLevel2;
    private javax.swing.JButton GBLevel3;
    private javax.swing.JButton Menu;
    private javax.swing.JButton SBName;
    private javax.swing.JButton SBScore;
    private javax.swing.JTable ScoreTable;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
